export enum tipoAeronave { COMERCIAL = 'COMERCIAL', MILITAR = 'MILITAR' }
export enum TipoPeca { NACIONAL = 'NACIONAL', IMPORTADA = 'IMPORTADA' }
export enum StatusPeca { EM_PRODUCAO = 'EM PRODUCAO', EM_TRANSPORTE = 'EM TRANSPORTE', PRONTA = 'PRONTA' }
export enum StatusEtapa { PENDENTE = 'PENDENTE', EM_ANDAMENTO = 'EM ANDAMENTO', CONCLUIDA = 'CONCLUIDA' }
export enum NivelPermissao { ADMINISTRADOR = 'ADMINISTRADOR', ENGENHEIRO = 'ENGENHEIRO', OPERADOR = 'OPERADOR' }
export enum TipoTeste { ELETRICO = 'ELETRICO', HIDRAULICO = 'HIDRAULICO', AERODINAMICO = 'AERODINAMICO' }
export enum ResultadoTeste { APROVADO = 'APROVADO', REPROVADO = 'REPROVADO' }